services:

    gearman_primary:
        build:
            context: docker
            dockerfile: gearman.Dockerfile
        ports:
            - "4731:4730"

    gearman_secondary:
        build:
            context: docker
            dockerfile: gearman.Dockerfile
        ports:
            - "4732:4730"
    
    worker_example:
        build:
            context: .
            dockerfile: Samples/WorkerExample/Dockerfile
        deploy:
            resources:
                limits:
                    memory: 256M