services:

    gearman_primary:
        build:
            context: docker
            dockerfile: gearman.Dockerfile
        ports:
            - "4731:4730"

    gearman_secondary:
        build:
            context: docker
            dockerfile: gearman.Dockerfile
        ports:
            - "4732:4730"